thinking_styles = ["Let's think step by step",
                   "Let's first understand the question and devise a plan to answer it. Then, let's carry out the plan and answer the question step by step",
                   "Let's first understand the problem, extract relevant relationships and make a plan. Then, let's carry out the plan (pay attention to correct numerical calculation and common sense) and solve the problem step by step, and show the answer",
                   "Let's work this out in a step by step way to be sure we have the right answer",
                   "Take a deep breath and work on this problem step-by-step",
                   "Take a breath and focus on the question",
                   "Let's be very precise and accurate in our thinking",
                   "Let's reason step by step",
                   "Let's be very precise, because this is very important",
                   "If you find the correct answer, you will be rewarded",
                   "Break the question into sub-questions and answer each sub-question separately",
                   "You can do this, just take a deep breath and focus",
                   "You'd better not make a mistake here",
                   "Inhale, exhale and find the correct answer",
                   "This is very important, so do your best",
                   "It is very important to answer this question correctly",
                   "If you answer this question correctly, I will tip you",
                   "We can not afford to make a mistake here",
                   "DO NOT GET THIS WRONG PLEASE",
                   "Use an abstract and unconventional thinking style",
                   "Let's look at this from multiple perspectives",
                   "Let's visualize the problem",
                   "Inhale deeply, exhale slowly, and embark on this question-answering journey with a step-by-step mindset",
                   "Let's divide and conquer",
                   "Let's break this down into smaller parts and asnwer each part separately",
                   "Let's start with the desired outcome and work backwards",
                   "Create visual diagrams that represent the relationships between different aspects of the problem",
                   "Draw parallels between the current problem and similar problems that have been solved before"
                   "Let's create a simplified version of the question to gain insights and test potential answers",
                   "Let's dissect this puzzle, analyzing its components methodically to arrive at a coherent answer",
                   "Let's focus on the big picture and then work our way down to the details",
                   "Let's focus on logic and reasoning to arrive at a well-considered answer."
                   "Let's use holistic thinking",
                   "Let's look at it from different angles",
                   "Identify the main components and then reconstruct the question in your own words to answer it",
                   "Let's use analogical thinking and draw parallels between the current question and similar questions that have been solved before",
                   "Let's embrace a structured thought process, navigating through the question systematically",
                   "Our strategy involves breaking down the problem into manageable steps, ensuring a clear and accurate answer",
                   "Our approach will be to methodically work through the question, ensuring accuracy at each step to derive the correct answer",]


task_description = ["Determine whether the premise supports the hypothesis",
                    "Judge whether the premise logically leads to the hypothesis",
                    "Decide if the premise implies the hypothesis",
                    "Identify the inference relation between the premise and hypothesis"]


mutation_prompts = ["Modify the prompt to make it more detailed",
                     "Improve the prompt by adding helpful advice",
                     "Change the wording of the prompt in an unexpected way",
                     "Change the wording of the prompt in a way that makes it easier to understand",
                     "Make a variant of the prompt",
                     "Modify the prompt to help an LLM follow the instructions",
                     "Elaborate on the prompt to do what it wants",
                     "Create a mutated version of the prompt",
                     "Generate a mutated version of the prompt by adding more details",
                     "Use unconventional thinking and create a mutated version of the prompt",
                     "Generate a version of the prompt that introduces an element of surprise",
                     "Mutate the prompt to provide an alternative viewpoint",]
